name: Deploy to AWS

on: push

jobs:
  package-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target=api -r ./api/requirements.txt
        working-directory: ./src
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
        working-directory: ./src/api
      - name: Zip package
        run: zip -r ../../api.zip *
        working-directory: ./src/api
      - name: Upload api folder zip
        uses: actions/upload-artifact@v1
        with:
          name: api
          path: api.zip

  package-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --target=ui -r ./ui/requirements.txt
        working-directory: ./src
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
        working-directory: ./src/ui
      - name: Zip package
        run: zip -r ../../ui.zip *
        working-directory: ./src/ui
      - name: Upload ui folder zip
        uses: actions/upload-artifact@v1
        with:
          name: ui
          path: ui.zip

  terraform-deploy:
    needs: [package-api, package-ui]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to AWS
        uses: will-goodman/actions/terraform@wg_terraform
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key_id: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          default_region: ${{ secrets.AWS_DEFAULT_REGION }}
